#!/usr/bin/env bash
# Install nginx on a web-01 server.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
