#!/usr/bin/env bash
# Install nginx on a web server and redirect.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Mauricio-KND permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
