#!/usr/bin/env bash
# Configures new Ubuntu machine to the requirements asked.
apt-get update
apt-get -y install nginx
http_header="add_header X-Served-By $HOSTNAME;"
sed -i "/sendfile on;/a $http_header" /etc/nginx/nginx.conf
service nginx restart
