#!/usr/bin/env bash
# Configures new Ubuntu machine to the requirements asked.
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i "26i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
