#!/usr/bin/env bash
# Install and configure HAproxy on your server.
apt-get update
apt-get -y install haproxy
printf "\nfrontend web_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web_backend\nbackend web_backend\n\tbalance roundrobin\n\tmode http\n\tserver 693-web-01 54.145.28.120\n\tserver 693-web-02 107.21.78.78\n" >> /etc/haproxy/haproxy.cfg
service haproxy start
