#!/usr/bin/env bash
# Install and configure HAproxy on your server.
apt-get update
apt-get -y install haproxy=1.6.\*
echo "frontend web_front                                                                     
   bind *:80                                                                                 
   mode http                                                                                 
   default_backend web-backend                                                               
   backend web-backend                                                                       
   balance roundrobin                                                                        
   mode http                                                                                 
   server web1 54.145.28.120:80 check                                                        
   server web2 35.229.33.79:80 check                                                         
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
