#!/usr/bin/env bash
#Displays: To infinity and beyond indefinitely. Sleep 2 between iteration. I am invincible!!! receiving SIGTERM signal.
trap "echo I am invincible!!!" SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
