#!/usr/bin/env bash
#Displays time 12 hours 59 minutes. Hours from 0-12. Minutes 1-59
((h=0)); while ((h <= 12)); do
            ((m=1))
            echo "Hour: $h"
            while ((m < 60)); do
      	    echo "$m"
	        ((m++)); done
            ((h++)); done
